openapi: 3.0.0
info:
  title: Items API
  description: API for performing CRUD operations on items
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /api/items:
    get:
      summary: Get all items
      responses:
        '200':
          description: Success
    post:
      summary: Create a new item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '201':
          description: Created
  /api/items/{id}:
    get:
      summary: Get an item by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
        '404':
          description: Not Found
    put:
      summary: Update an item
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '200':
          description: Updated
    delete:
      summary: Delete an item
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Deleted

components:
  schemas:
    Item:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: number
        quantity:
          type: number
        category:
          type: string